### ISSUE TITLE
Swipe on buttonPress

### ISSUE THREAD

**Issue by riobijanero** [CaiJingLong/flutter_page_indicator#12]
I'd like to swipe write and and left not on a button Press.
Is there a function I can trigger?

**Comment by CaiJingLong** [comment]
I don't understand what you mean.

**Comment by lets-swapcode** [comment]
The page changes on swipe now. we want a button on which it can change same as swipe.

**Comment by CaiJingLong** [comment]
Need a callback to manually trigger the refresh of the indicator?

**Comment by CaiJingLong** [comment]
Support force refrsh change in #14 .
Update version to 0.2.1 , and see usage in [readme#force-refersh-state](https://github.com/CaiJingLong/flutter_page_indicator#force-refersh-state).
