### ISSUE TITLE
Type 'FixedScrollMetrics' is not a subtype of type 'PageMetrics'

### ISSUE THREAD

**Issue by agustincards14** [CaiJingLong/flutter_page_indicator#23]
Hello,

This seems to be a problem when using a scroll view (ListView in my case) as a PageView child and scrolling vertically (or perpendicular) to the PageView orientation. 

Below is the stack trace:
`I/flutter ( 4144): ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════════════════════════════════════════════════════════════════
I/flutter ( 4144): The following _TypeError was thrown while handling a gesture:
I/flutter ( 4144): type 'FixedScrollMetrics' is not a subtype of type 'PageMetrics'
I/flutter ( 4144): 
I/flutter ( 4144): When the exception was thrown, this was the stack:
I/flutter ( 4144): #0      PageContainerState._onScroll (package:page_indicator/src/container.dart:114:25)
I/flutter ( 4144): #1      NotificationListener._dispatch (package:flutter/src/widgets/notification_listener.dart:129:41)
I/flutter ( 4144): #2      Notification.visitAncestor (package:flutter/src/widgets/notification_listener.dart:47:20)
I/flutter ( 4144): #3      ViewportNotificationMixin.visitAncestor (package:flutter/src/widgets/scroll_notification.dart:31:18)
I/flutter ( 4144): #4      Element.visitAncestorElements (package:flutter/src/widgets/framework.dart:3989:39)
I/flutter ( 4144): #5      Notification.dispatch (package:flutter/src/widgets/notification_listener.dart:63:13)
I/flutter ( 4144): #6      DragScrollActivity.dispatchScrollUpdateNotification (package:flutter/src/widgets/scroll_activity.dart:443:139)
I/flutter ( 4144): #7      ScrollPosition.didUpdateScrollPositionBy (package:flutter/src/widgets/scroll_position.dart:721:14)
I/flutter ( 4144): #8      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:245:9)
I/flutter ( 4144): #9      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:83:18)
I/flutter ( 4144): #10     ScrollPositionWithSingleContext.applyUserOffset (package:flutter/src/widgets/scroll_position_with_single_context.dart:126:5)
I/flutter ( 4144): #11     ScrollDragController.update (package:flutter/src/widgets/scroll_activity.dart:372:14)
I/flutter ( 4144): #12     ScrollableState._handleDragUpdate (package:flutter/src/widgets/scrollable.dart:543:12)
I/flutter ( 4144): #13     DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:403:54)
I/flutter ( 4144): #14     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
I/flutter ( 4144): #15     DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:403:7)
I/flutter ( 4144): #16     DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:258:9)
I/flutter ( 4144): #17     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
I/flutter ( 4144): #18     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
I/flutter ( 4144): #19     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)
I/flutter ( 4144): #20     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
I/flutter ( 4144): #21     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
I/flutter ( 4144): #22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
I/flutter ( 4144): #23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
I/flutter ( 4144): #24     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
I/flutter ( 4144): #25     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
I/flutter ( 4144): #26     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
I/flutter ( 4144): #30     _invoke1 (dart:ui/hooks.dart:275:10)
I/flutter ( 4144): #31     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)
I/flutter ( 4144): (elided 3 frames from dart:async)
I/flutter ( 4144): 
I/flutter ( 4144): Handler: "onUpdate"
I/flutter ( 4144): Recognizer:
I/flutter ( 4144):   VerticalDragGestureRecognizer#89b5b`

**Comment by MartinhoMCM** [comment]
I found the same problem.

**Comment by JessicaShalomG** [comment]
same issue

**Comment by ghost** [comment]
This should be fixed now by version 0.4.1
