### ISSUE TITLE
Bug(Maybe)

### ISSUE THREAD

**Issue by yongping95** [CaiJingLong/flutter_page_indicator#4]
Hi, I am pretty new to flutter and I saw this package today and started using it. I am using it in a horizontal page view to display pictures, and I am also implementing a swipe to dismiss when swiping upwards. The problem occurs when I delete the last picture/page, the indicator doesn't refresh even though I remove the image from the list inside the setstate. The indicator will always be indicating the last image and the number of dots is always one more than the number of pictures that I have. I did set the length to the length of the list of picture and I do see that the number updates.

**Comment by CaiJingLong** [comment]
Can you use a simple Example to reproduce the bug?
Create a reproducible code, and I'll try to solve it, or locate whether it's a library or not.

**Comment by CaiJingLong** [comment]
I'll close this issue first. If you make new progress, please reopen it.
