### ISSUE TITLE
Example is incorrect on flutter plugin site

### ISSUE THREAD

**Issue by jaceshim** [CaiJingLong/flutter_page_indicator#5]
Below link is image that is captured on flutter plugin site.
[captured image](https://imgur.com/gPQ1GLC)

`import 'package:page_view_indicator/page_view_indicator.dart';`

is incorrect!.

change to `import 'package:page_indicator/page_indicator.dart';`

Best Regards.

**Comment by CaiJingLong** [comment]
Thx for issue.

I fixed this on github, not on pub.
It was thought that it would be revised with the next version, but no new problems had been found for a long time, so it was put on hold for the time being.
Let me upload a small version to fix this problem.

**Comment by CaiJingLong** [comment]
fixed
