### ISSUE TITLE
Center the pageController

### ISSUE THREAD

**Issue by tounoussiKhalid** [CaiJingLong/flutter_page_indicator#9]
hello, thanks first, I want ot ask you, when I use this and make it in the center it actually hide a field, what to do ?

**Comment by CaiJingLong** [comment]
I may not understand what you mean.
Do you have screenshots and code to help me understand what you mean?

**Comment by tounoussiKhalid** [comment]
actually I want to make the dots just like this, because it actually hide the fields when I try to make between two widgets. 
![Screenshot_2019-04-18-19-29-56](https://user-images.githubusercontent.com/44621176/56383048-c7a52b00-6210-11e9-827e-f7050b60785e.png)

**Comment by CaiJingLong** [comment]
![image](https://user-images.githubusercontent.com/14145407/56399121-c3175b80-627e-11e9-8cc0-94db7929e2bc.png)

I marked areas 1 and 2.
Are these two areas PageView item or PageView level Widget?

**Comment by CaiJingLong** [comment]
Let me guess what you mean.
Dots are covered?
I created an example to get the following screenshot:
![image](https://user-images.githubusercontent.com/14145407/56399806-d9bfb180-6282-11e9-9786-118567532d3e.png)
![image](https://user-images.githubusercontent.com/14145407/56399800-d298a380-6282-11e9-991f-a4b9763c4eaf.png)

```dart
import 'package:flutter/material.dart';
import 'package:page_indicator/page_indicator.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key}) : super(key: key);

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  static const colors = <Color>[
    Colors.lightBlue,
    Colors.deepOrange,
    Colors.lightGreen,
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      body: Stack(
        children: <Widget>[
          Container(
            child: PageIndicatorContainer(
              pageView: PageView.builder(
                itemBuilder: _buildItem,
                itemCount: 5,
              ),
              length: 5,
              padding: const EdgeInsets.only(bottom: 180),
            ),
          ),
          Align(
            child: Padding(
              padding: const EdgeInsets.only(bottom: 120.0),
              child: RaisedButton(
                color: Colors.white,
                child: Text("Same level as pageview"),
                onPressed: () {},
              ),
            ),
            alignment: Alignment.bottomCenter,
          ),
        ],
      ),
    );
  }

  Widget _buildItem(BuildContext context, int index) {
    var w = Container(
      color: colors[index % colors.length],
      child: Center(
        child: Text("I 'm $index page"),
      ),
    );

    if (index == 0) {
      return Stack(
        children: <Widget>[
          w,
          Align(
            child: RaisedButton(
              color: Colors.grey.withGreen(30),
              child: Text(
                "This button belongs to item of PageView.",
                style: TextStyle(color: Colors.white),
              ),
              onPressed: () {},
            ),
            alignment: Alignment(0, 0.9),
          ),
        ],
      );
    }

    return w;
  }
}
```

**Comment by tounoussiKhalid** [comment]
Actually, the whole page that I have sent is a child of page view, and 1 and 2 are just child of the child of the page view , so they are just widgets . I have made 5 child for my page view with an horizontal scroll. 
what I want is I dont want that the page indicator  hide one of my widgets in any of children of my page view and mostley to be responsive even we change the environnement.

**Comment by CaiJingLong** [comment]
I don't understand what you expect.
Through screenshots and descriptions, I don't know where your problem is.

**Comment by tounoussiKhalid** [comment]
Okey, Imagine we're running the app on a small phone, and I have position the indicator between 1 and 2, I think that it will hide fields, so how to make its position responsive: that means it will be always between the two widgets ?

**Comment by tounoussiKhalid** [comment]
This is the problem : you see in the picture , I know I can modigy it's position, but it will hide fields in other pages in my page view.
![Screenshot_2019-04-19-11-01-35](https://user-images.githubusercontent.com/44621176/56419630-d16f7280-6292-11e9-9c72-4519874d1100.png)

**Comment by CaiJingLong** [comment]
Maybe I can't help you implement the complete code, but I can give you some hints.
How do you layout your blue buttons? Calculate the padding by screen size before layout.
Then use the padding and position attributes to layout indicator.

**Comment by CaiJingLong** [comment]
It has been a long time, no change. Close it.
